name: bactinfection
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - voila
  - nodejs
  - pip
  - pip:
    - python-bioformats
    - oiffile
    - napari
    - scikit-learn
    - git+https://github.com/guiwitz/Bactinfection.git@master#egg=bactinfection&subdirectory=bactinfection
#jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter labextension install @jupyter-voila/jupyterlab-preview